import type { Config } from "tailwindcss";
import tailwindcssAnimate from "tailwindcss-animate";

export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/modules/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        plusJakartaSans: ["Plus Jakarta Sans", "sans-serif"],
        jakarta: "var(--font-plus-jakarta-sans)",
      },
      screens: {
        xxs: "375px",
        xs: "450px",
        s: "550px",
        sm: "640px",
        md: "768px",
        nanggung: "880px",
        lg: "1024px",
        xl: "1280px",
        "2xl": "1536px",
        "3xl": "2100px",
      },
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        neutral: {
          "25": "#FCFCFD",
          "50": "#F8FAFC",
          "100": "#EEF2F6",
          "200": "#E3E8EF",
          "300": "#CDD5DF",
          "400": "#9AA4B2",
          "500": "#697586",
          "600": "#4B5565",
          "700": "#364152",
          "800": "#202939",
          "900": "#121926",
        },
        blue: {
          "25": "#F5F8FF",
          "50": "#EFF4FF",
          "100": "#D1E0FF",
          "200": "#B2CCFF",
          "300": "#84ADFF",
          "400": "#528BFF",
          "500": "#2970FF",
          "600": "#155EEF",
          "700": "#004EEB",
          "800": "#0040C1",
          "900": "#00359E",
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        success: {
          "25": "#F6FEF9",
          "50": "#EDFCF2",
          "100": "#D3F8DF",
          "200": "#AAFOC4",
          "300": "#73E2A3",
          "400": "#73E2A3",
          "500": "#16B364",
          "600": "#099250",
          "700": "#087443",
          "800": "#095C37",
          "900": "#084C2E",
        },
        error: {
          "25": "#FFF8FA",
          "50": "#FEF3F2",
          "100": "#FEE4E2",
          "200": "#FECDCA",
          "300": "#FDA29B",
          "400": "#F97066",
          "500": "#F04438",
          "600": "#D92D20",
          "700": "#B42318",
          "800": "#912018",
          "900": "#7A271A",
        },
        primary: {
            DEFAULT: "hsl(var(--primary))",
            foreground: "hsl(var(--primary-foreground))",
          },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },

        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          "1": "hsl(var(--chart-1))",
          "2": "hsl(var(--chart-2))",
          "3": "hsl(var(--chart-3))",
          "4": "hsl(var(--chart-4))",
          "5": "hsl(var(--chart-5))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  plugins: [tailwindcssAnimate],
} satisfies Config;
